#!/usr/bin/env ruby
#^syntax detection

site 'http://community.opscode.com/api/v1'

cookbook 'apache2'
cookbook 'php'
cookbook 'database'
cookbook 'apt'


cookbook 'postgresql',
   :git => 'https://github.com/lukasz-kaniowski/postgresql'
